// <auto-generated />
using System;
using DempApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DempApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112185449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DempApi.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InsertedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Description = "Information Technology",
                            InsertedById = 1,
                            InsertedDate = new DateTime(2025, 11, 12, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6679),
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Description = "Human Resources",
                            InsertedById = 1,
                            InsertedDate = new DateTime(2025, 11, 12, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6681),
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Description = "Finance Department",
                            InsertedById = 1,
                            InsertedDate = new DateTime(2025, 11, 12, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6682),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Deleted = true,
                            Description = "Marketing Department (Deleted)",
                            InsertedById = 1,
                            InsertedDate = new DateTime(2025, 10, 13, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6684),
                            Name = "Marketing",
                            UpdatedById = 1,
                            UpdatedDate = new DateTime(2025, 11, 11, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6695)
                        });
                });

            modelBuilder.Entity("DempApi.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsertedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DempApi.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InsertedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Description = "Develops software",
                            InsertedById = 1,
                            InsertedDate = new DateTime(2025, 11, 12, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6864),
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Description = "Senior developer",
                            InsertedById = 1,
                            InsertedDate = new DateTime(2025, 11, 12, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6866),
                            Title = "Senior Software Engineer"
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Description = "Manages HR",
                            InsertedById = 1,
                            InsertedDate = new DateTime(2025, 11, 12, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6868),
                            Title = "HR Manager"
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Description = "Manages finances",
                            InsertedById = 1,
                            InsertedDate = new DateTime(2025, 11, 12, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6869),
                            Title = "Accountant"
                        },
                        new
                        {
                            Id = 5,
                            Deleted = true,
                            Description = "Manages marketing (Deleted)",
                            InsertedById = 1,
                            InsertedDate = new DateTime(2025, 10, 13, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6870),
                            Title = "Marketing Manager",
                            UpdatedById = 1,
                            UpdatedDate = new DateTime(2025, 11, 10, 18, 54, 44, 732, DateTimeKind.Utc).AddTicks(6871)
                        });
                });

            modelBuilder.Entity("DempApi.Domain.Entities.Employee", b =>
                {
                    b.HasOne("DempApi.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DempApi.Domain.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("DempApi.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DempApi.Domain.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
